---
title: "Chap1: Probability"
author: "Anthony El Khoueiry"
date: ""
format: 
    html:
      code-line-numbers: true
      df-print: paged

---
----

#### **Part 1.1**
```{r}

# Given probabilities
P_S <- 0.3
P_T_S <- 0.2
P_T_S_Bar <- 0.6
P_S_Bar <- 1 - P_S
P_T_Bar_S <- 1 - P_T_S
P_T_Bar_S_Bar <- 1 - P_T_S_Bar

# The conditional probabilities are:
P_T_inter_S <- P_S * P_T_S
P_T_inter_S_Bar <- P_S_Bar * P_T_S_Bar
P_T_Bar_inter_S <- P_S * P_T_Bar_S
P_T_Bar_inter_S_Bar <- P_S_Bar * P_T_Bar_S_Bar

# The results to be printed:
print(P_T_inter_S)
print(P_T_inter_S_Bar)
print(P_T_Bar_inter_S)
print(P_T_Bar_inter_S_Bar)
```
#### **Part 1.2**
```{r}
# Libraries
library(tidyverse)
library(ggVennDiagram)

# Number of observations
n <- 1000

# Tibble with user information:
app_usage <- tibble(
  user_id = 1:n,
  smartphone = rbinom(n, 1, 0.4),
  tablet = ifelse(smartphone == 1, rbinom(n, 1, 0.2), rbinom(n, 1, 0.5)),
  computer = ifelse(tablet == 1, rbinom(n, 1, 0.1), rbinom(n, 1, 0.3))
)

#At least one device is used per user:
app_usage <- app_usage %>%
  rowwise() %>% 
  mutate(smartphone = ifelse(sum(smartphone, tablet, computer) == 0, 1, smartphone))

# the first ten rows of the data:
head(app_usage, 10)

# column sums:
colSums(app_usage)

# sets of phone, tablet, and computer users:
set_phon <- which(app_usage$smartphone == 1)
set_tabl <- which(app_usage$tablet == 1)
set_comp <- which(app_usage$computer == 1)

# List of all sets:
sets_all <- list(set_phon, set_tabl, set_comp)

# Plot Venn diagram:
ggVennDiagram(sets_all, category.names = c("Smartphone", "Tablet", "Computer"),
              label_percent_digit = 2) +
  theme(legend.position = "none", 
        panel.background = element_rect("green"),
        strip.background = element_rect("red")) +
  scale_x_continuous(expand = expansion(mult = .24))

# the intersection of sets (users using all three devices):
set_all_three <- Reduce(intersect, sets_all)
percentage_all_three <- length(set_all_three) / n * 100
cat("Percentage of customers using all three devices:", round(percentage_all_three, 2), "%\n")

# the union of sets (users using at least two devices):
set_at_least_two <- union(intersect(set_phon, set_tabl), union(intersect(set_phon, set_comp), intersect(set_comp, set_tabl)))
percentage_at_least_two <- length(set_at_least_two) / n * 100
cat("Percentage of customers using at least two devices:", round(percentage_at_least_two, 2), "%\n")

# the sets of users using each device exclusively
set_only_phon <- set_phon[!(set_phon %in% set_tabl) & !(set_phon %in% set_comp)]
set_only_tabl <- set_tabl[!(set_tabl %in% set_phon) & !(set_tabl %in% set_comp)]
set_only_comp <- set_comp[!(set_comp %in% set_phon) & !(set_comp %in% set_tabl)]
percentage_only_one <- (length(set_only_phon) + length(set_only_tabl) + length(set_only_comp)) / n * 100
cat("Percentage of customers using only one device:", round(percentage_only_one, 2), "%\n")
```
#### **Part 1.3**
```{r}
# Given probabilities
prob_A <- 0.04
prob_B_given_A <- 0.97
prob_not_B_given_A <- 0.01
prob_not_A <- 1 - prob_A
prob_not_B_given_not_A <- 1 - prob_B_given_A
prob_not_B_given_not_A_not <- 1 - prob_not_B_given_A

# overall probability of B
prob_B <- (prob_B_given_A * prob_A) + (prob_not_B_given_A * prob_not_A)

# conditional probability of not A given B
prob_not_A_given_B <- (prob_not_B_given_A * prob_not_A) / prob_B

# conditional probability of A given B
prob_A_given_B <- (prob_B_given_A * prob_A) / prob_B

# results
print(prob_not_A_given_B)
print(prob_A_given_B)

```